config/routes.rb
Rails.application.routes.draw do
  resources :customer_products
  resources :products
  resources :product_categories
  resources :companies
  resources :sizes
  resources :orders
  resources :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
		has_many :orders
	has_many :customer_products
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :shop_name, :city, :street, :province, :postal_code, :primary_contact, :secondary_contact, :vat_no, :email)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :shop_name %>
    <%= form.text_field :shop_name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :province %>
    <%= form.text_field :province %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.number_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :primary_contact %>
    <%= form.number_field :primary_contact %>
  </div>

  <div class="field">
    <%= form.label :secondary_contact %>
    <%= form.number_field :secondary_contact %>
  </div>

  <div class="field">
    <%= form.label :vat_no %>
    <%= form.number_field :vat_no %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Shop name</th>
      <th>City</th>
      <th>Street</th>
      <th>Province</th>
      <th>Postal code</th>
      <th>Primary contact</th>
      <th>Secondary contact</th>
      <th>Vat no</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.shop_name %></td>
        <td><%= customer.city %></td>
        <td><%= customer.street %></td>
        <td><%= customer.province %></td>
        <td><%= customer.postal_code %></td>
        <td><%= customer.primary_contact %></td>
        <td><%= customer.secondary_contact %></td>
        <td><%= customer.vat_no %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Shop name:</strong>
  <%= @customer.shop_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Street:</strong>
  <%= @customer.street %>
</p>

<p>
  <strong>Province:</strong>
  <%= @customer.province %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @customer.postal_code %>
</p>

<p>
  <strong>Primary contact:</strong>
  <%= @customer.primary_contact %>
</p>

<p>
  <strong>Secondary contact:</strong>
  <%= @customer.secondary_contact %>
</p>

<p>
  <strong>Vat no:</strong>
  <%= @customer.vat_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>