config/routes.rb
Rails.application.routes.draw do
  resources :customer_products
  resources :products
  resources :product_categories
  resources :companies
  resources :sizes
  resources :orders
  resources :customers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer_product.rb
class CustomerProduct < ApplicationRecord
		belongs_to :product
	belongs_to :customer
end

app/controllers/customer_products_controller.rb
class CustomerProductsController < ApplicationController
  before_action :set_customer_product, only: [:show, :edit, :update, :destroy]

  # GET /customer_products
  # GET /customer_products.json
  def index
    @customer_products = CustomerProduct.all
  end

  # GET /customer_products/1
  # GET /customer_products/1.json
  def show
  end

  # GET /customer_products/new
  def new
    @customer_product = CustomerProduct.new
  end

  # GET /customer_products/1/edit
  def edit
  end

  # POST /customer_products
  # POST /customer_products.json
  def create
    @customer_product = CustomerProduct.new(customer_product_params)

    respond_to do |format|
      if @customer_product.save
        format.html { redirect_to @customer_product, notice: 'Customer product was successfully created.' }
        format.json { render :show, status: :created, location: @customer_product }
      else
        format.html { render :new }
        format.json { render json: @customer_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_products/1
  # PATCH/PUT /customer_products/1.json
  def update
    respond_to do |format|
      if @customer_product.update(customer_product_params)
        format.html { redirect_to @customer_product, notice: 'Customer product was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_product }
      else
        format.html { render :edit }
        format.json { render json: @customer_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_products/1
  # DELETE /customer_products/1.json
  def destroy
    @customer_product.destroy
    respond_to do |format|
      format.html { redirect_to customer_products_url, notice: 'Customer product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_product
      @customer_product = CustomerProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_product_params
      params.require(:customer_product).permit(:price)
    end
end

app/helpers/customer_products_helper.rb
module CustomerProductsHelper
end

app/views/customer_products/_form.html.erb
<%= form_with(model: customer_product, local: true) do |form| %>
  <% if customer_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_product.errors.count, "error") %> prohibited this customer_product from being saved:</h2>

      <ul>
        <% customer_product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customer_products/edit.html.erb
<h1>Editing Customer Product</h1>

<%= render 'form', customer_product: @customer_product %>

<%= link_to 'Show', @customer_product %> |
<%= link_to 'Back', customer_products_path %>

app/views/customer_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Products</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_products.each do |customer_product| %>
      <tr>
        <td><%= customer_product.price %></td>
        <td><%= link_to 'Show', customer_product %></td>
        <td><%= link_to 'Edit', edit_customer_product_path(customer_product) %></td>
        <td><%= link_to 'Destroy', customer_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer Product', new_customer_product_path %>

app/views/customer_products/new.html.erb
<h1>New Customer Product</h1>

<%= render 'form', customer_product: @customer_product %>

<%= link_to 'Back', customer_products_path %>

app/views/customer_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @customer_product.price %>
</p>

<%= link_to 'Edit', edit_customer_product_path(@customer_product) %> |
<%= link_to 'Back', customer_products_path %>